author: Xzit
email: hi@xzit.dev
seo:
  title: Xzit
  description: >-
    Acompáñame en mi diario de desarrollo web donde construyo startups reales
    como Emprende.uno y Cosplay.land. Aprende sobre desarrollo, producto y
    lanzamientos.
navbar:
  github: https://github.com/xzit/www
footer:
  timezone: America/Mexico_City
  location: Ciudad del Carmen, MX
  coordinates: 18.6510, -91.8025
