author: Xzit
email: hi@xzit.dev
seo:
  title: Xzit // Frontend Developer & Entrepreneur building real startups
  description: >-
    I'm a frontend developer and startup builder sharing my journey through
    real-world web development. Follow along as I build and launch digital
    products like Emprende.uno and Cosplay.land. Learn about modern frontend
    development, product design, and startup launches — from idea to production.
navbar:
  github: https://github.com/xzit/www
footer:
  timezone: America/Mexico_City
  location: Ciudad del Carmen, MX
  coordinates: 18.6510, -91.8025
